#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub enum Item {
    #[default]
    Empty = -1,
    RichAir = 0,
    ManaCrystal,
    LiquidCurse,
    ManaDust,
    SilicaPowder,
    ObsidianPlate,
    CopperCoin,
    SilverCoin,
    GoldCoin,
    TaintedWater,
    ChaosSalt,
    VialOfBlood,
    LifeForce,
    CongealedFleshmatter,
    SentientMeat,
    WeakManaGem,
    PureManaGem,
    GloomShard,
    BrightShard,
    EqualizedOrb,
    AdamantineBar,
    AstralSheet,
    ElementalChassis,
    EnergizedSpark,
    ImmaculateSoul,
    Phylactery,
}
